name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-dev --no-progress --optimize-autoloader

      - name: Create release archive
        run: |
          zip -r apiera-sdk.zip . -x ".git/*" ".github/*" "tests/*" "phpunit.xml" "phpstan.neon" "phpcs.xml" "*.md"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: apiera-sdk.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update version constant
        run: |
          echo "<?php return '${{ steps.get_version.outputs.VERSION }}';" > version.php