# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches: [ master, 'develop/*', 'feature/*', 'bug/*', 'test/*' ]
  pull_request:
    branches: [ master, 'develop/*', 'feature/*', 'bug/*', 'test/*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3']

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: composer test

---
# .github/workflows/static-analysis.yml
name: Static Analysis

on:
  push:
    branches: [ master, 'develop/*', 'feature/*', 'bug/*', 'test/*' ]
  pull_request:
    branches: [ master, 'develop/*', 'feature/*', 'bug/*', 'test/*' ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHPStan
        run: composer static:analyse

---
# .github/workflows/code-style.yml
name: Code Style

on:
  push:
    branches: [ master, 'develop/*', 'feature/*', 'bug/*', 'test/*' ]
  pull_request:
    branches: [ master, 'develop/*', 'feature/*', 'bug/*', 'test/*' ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Check coding standards
        run: composer cs:check